# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(f"{len(X_train)}, {len(X_test)}, {len(y_train)}, {len(y_test)}")

120, 30, 120, 30


In [7]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [8]:
standardized_X_test[0:10,]

array([[ 0.6340746 ,  0.59677617,  1.06775748,  1.47104488],
       [-1.11974876, -0.39785078, -1.0820898 , -1.06801888],
       [ 0.49916511, -0.89516426,  0.31531094,  0.2619669 ],
       [ 0.09443664, -0.89516426,  0.90651894,  1.59195268],
       [-0.5801108 ,  1.34274638, -1.02834362, -1.06801888],
       [ 0.90389358, -0.89516426,  1.17524985,  1.35013708],
       [-0.84992978,  1.59140312, -1.02834362, -0.94711109],
       [-0.04047285, -0.89516426,  0.58404185,  0.2619669 ],
       [-0.44520131,  1.84005986, -0.92085125, -0.82620329],
       [ 0.36425562, -2.38710468,  0.31531094, -0.1007565 ]])

In [9]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [10]:
y_pred = perceptron.predict(standardized_X_test)

In [11]:
print(y_test)

[2 0 1 2 0 2 0 1 0 1 0 0 1 0 2 0 0 1 2 0 1 2 2 0 0 2 0 2 0 2]


In [12]:
print(y_pred)

[2 0 1 2 0 2 0 1 0 1 0 0 2 0 2 0 0 2 2 0 2 2 2 0 0 2 0 2 0 2]


In [13]:
print(classification_report(y_test, y_pred))

precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.50      0.67         6
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.83      0.85        30
weighted avg       0.92      0.90      0.89        30

